      program main
      implicit real*8(a-h,o-z)
c     real*4 r
      parameter(ndata=29999)
      data bvalue,ctmg   / 1.0, 3.5 /
      data a,b,c,d,p / 0.00200,.00400,.00300,2.40000,1.30000 /
c     data a,b,c,d,p / 0.02000,.04000,.00300,0.40000,1.30000 /
      data nd / 1000 /
c     data xm / ndata*0.0 /
      dimension xx(ndata),xm(ndata),zz(ndata),xmo(ndata)
      character line*128
      character kfile*128,amag*128

      nloop=1
      narg=iargc()
      call getarg(2,line)
      read(line,*) nseed
      if ( narg .gt. 2 ) then
	call getarg(3,line)
        read(line,*) nloop
      endif
      call getarg(1,line)
      if ( nseed .gt. 0 ) then
         do i=1,nseed
           call pseudo(r)
         enddo
      endif

      DO iii=1,nloop  !nloop
cc      open(unit=2,file='etasim.open')
      open(unit=2,file=line)
      read(2,*) ic,bvalue
      read(2,*) tstart,nd
      read(2,*) ctmg,rfmg
      read(2,*) a,b,c,d,p
      if ( ic .eq. 0 ) then
        read(2,*) xmainshock
      endif
      close(2)
      beta=bvalue*log(10.)
      rho=be*(p-1)*c**(p-1)/(beta-d)
      write(6,*) 'productivity', beta,d,c,p,rho
      jend=0
      if(tstart.gt.0.0) then
        open(unit=10,file='work.etas')
        read(10,1009) fmt
        j=0
   46   continue
        read(10,*, end=45) idum,e,en,xmi,zzi,depi
        if(zzi.gt.tstart) go to 45
        j=j+1
        xm(j)=xmi
        zz(j)=zzi
        go to 46
   45   continue
        jend=j
        close(10)
      endif
c     write(6,*) 'ic',ic,iend
      if(ic.eq.0) then
c       do 40 i=1,nd
c     magnitude simulation
       do 40 i=jend+1,nd
          call pseudo(r)
c          xm(i)=-log10(r)/bvalue +ctmg
c     -0.05は，マグニチュードが，0.1刻みであることを考慮している．
          xmag=-log10(r)/bvalue +ctmg -0.05
c          write(amag,'(f6.2)') xmag
          write(amag,'(f5.1)') xmag
          read(amag,*) xm(i)
          write(6,*) i,xm(i)
c       stop 4040
   40   continue
      else   ! ic=1 or 2
        open(unit=10,file='work.etas')
        read(10,1009) fmt
        write(6,1009) fmt
 1009   format(a)
        i=1
        jend=0
   50   continue
        read(10,*, end=60) idum,e,en,xmi,zzi,depi,iyr,mo,iday
 1008   format(i5,4f12.5,f5.0)
c         if(xmi.lt.ctmg) go to 50
c         if(zzi.lt.tstart) go to 50
c         write(6,1007) idum,e,en,xmi,zzi,depi,iyr,mo,iday
          xm(i)=xmi
          zz(i)=zzi
          if(ic.eq.2) xmo(i)=xmi
c         write(6,*) i,idum
          if(zzi.lt.tstart) jend=jend+1
          i=i+1
          go to 50
   60   continue
        close(10)
        nd=i-1
        if(ic.eq.2) then
        do 61 i=jend+1,nd
          call pseudo(r)
          ir=r*(nd-jend)+jend+1
          if(ir.gt.nd) ir=nd
          xm(i)=xmo(ir)
c         write(6,*) i,ir,nd,jend,r,xm(i),r*(nd-jend)
   61   continue
        end if
      endif
      write(6,1002) nd
c     stop
c     write(6,1001) (xm(i),i=1,nd)
 1001 format(8f10.5)
 1002 format(i10)
      write(6,*) 'b-value =',bvalue, 'cutoff magnitude=', ctmg
      write(6,*) 'a,b,c,d,p,bvalue ='
      write(6,1001) a,b,c,d,p,bvalue
!     if(ic.eq.0 .and. tstart.le.0.0) then
!       x=0.0
!       xity=a
!       i=1
!     else
!       i=1
        do 70 i=1,jend
          xx(i)=zz(i)
   70   continue
        if ( ic .eq. 0 ) then
	    xx(1)=0.0
c            xity=a   ! mu
c            xity=0.5   ! mu
            x=0.0
            i=1
            xm(1)=xmainshock
            call fx(i,x,a,b,c,d,p,rfmg,xx,xm,xity)
        endif
        if(jend.eq.0) then
          x=0.0
          i=1
        else
          x=xx(jend)
          i=jend+1
        endif
        if(i.gt.1) call fx(i-1,x,a,b,c,d,p,rfmg,xx,xm,xity)
c       write(6,*) i,x,xity
!     endif
   10 continue
      uity=xity
   20 continue
      call pseudo(r)
      e=-log(r)/uity
c     write(6,*) e,r,uity
      x=x+e
c     write(6,*) 'r',r,e,x,uity
      if(i.gt.1) call fx(i-1,x,a,b,c,d,p,rfmg,xx,xm,xity)
      probx=xity/uity
c     write(6,*) i, probx
      if(probx.gt.1.d0) write(6,*) 'prob>1', probx
      if(probx.gt.1.d0) stop 119
      call pseudo(r)
      if(r.gt.probx) go to 10
      xx(i)=x
      if(i.eq.1) write(6,*) 'event#  occurrence time'
c     if(mod(i,10).eq.0) write(6,*) i,xx(i)
      if(mod(i,1).eq.0) write(6,*) i,xx(i)
      uity=xity+b/c**p*exp(d*(xm(i)-rfmg))
      if(i.ge.nd) go to 30
      i=i+1
      go to 20
c
   30 continue
      t=xx(i)+e
      nn=i
      if ( nloop .eq. 1 ) then
	kfile='work.etasim'
      else
        write(kfile,'(a12,i4.4)') 'work.etasim.', iii
      endif
      open(unit=1,file=kfile)
c      open(unit=1,file='work.etasim')
c     write(1,1004) nn,t,ctmg,bvalue
c     write(1,1006) a,b,c,d,p
c     write(1,*) '(5x,4f12.5,f5.0)'
*     write(1,1003) (i,xm(i),xx(i),i=1,nn)
      if(ic.eq.0) 
     & write(1,*) 'ETAS simlated data: MAGs generated by G-R'
      if(ic.eq.1) 
     & write(1,*) 'ETAS simlated data: MAGS from [work.etas]'
      if(ic.eq.2) 
     & write(1,*) 'ETAS simlated data: MAGS generated by bootstrap'
      zr=0.0
      izr=0
      write(1,1007) (i,zr,zr,xm(i),xx(i),zr,izr,izr,izr, i=1,nn)
      close(unit=1)
 1003 format(i5,24x,2f12.5)
 1007 format(i5,2f12.5, f6.2, f16.8, f7.2, i6,2i3)
 1004 format('simulated data',' N,T=',i5,f9.3,';   M>=',f4.2,
     &       ';   b-value=',f4.2)
 1006 format(' ETAS parameter; mu,K_0,c,alpha,p =',5f8.5)
 1005 format(1h ,6f13.4)
      ENDDO ! iii
      stop
      end
c
      subroutine fx(i,x,a,b,c,d,p,rfmg,xx,xm,xity)
      implicit real*8(a-h,o-z)
      dimension xx(1),xm(1)
      xity=a
ctren xity=a-x*0.2821d-6
      do 10 j=1,i
c     write(6,*) b,x,xx(j),c,p,d,xm(j),rfmg
   10 xity=xity+b/(x-xx(j)+c)**p*exp(d*(xm(j)-rfmg))
c     write(6,*) xity
      return
      end
      subroutine pseud0(r)
c     generation of pseudo-random numbers
c     data ir/584287/
      data ir/574289/
      ir=ir*48828125
      if(ir) 10,20,20
   10 ir=(ir+2147483647)+1
   20 r=float(ir)*0.4656613e-9
      return
      end
      subroutine pseudo(random)
c     wichmann+hill (1982) Appl. Statist 31
      real*8 random
      data ix,iy,iz /1992,1111,1151/
      ix=171*mod(ix,177)-2*(ix/177)
      iy=172*mod(iy,176)-35*(iy/176)
      iz=170*mod(iz,178)-63*(iz/178)
      if (ix.lt.0) ix=ix+30269
      if (iy.lt.0) iy=iy+30307
      if (iz.lt.0) iz=iz+30323
      random=mod(float(ix)/30269.0+float(iy)/30307.0+
     &            float(iz)/30323.0,1.0)
      return
      end
